/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.Vista;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;


/**
 *
 * @author sala
 */
public class consultaExt extends javax.swing.JInternalFrame{
public static final String URL = "jdbc:mysql://localhost:3306/hospital";
public static final String USERNAME="root";
public static final String PASSWORD="";
public static String  telefono=null; 
PreparedStatement ps;
ResultSet rs;
public static Connection getConection(){
    Connection con=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        con=(Connection) DriverManager.getConnection(URL , USERNAME, PASSWORD);
    } catch (Exception e){
        System.out.println(e.getMessage());
    }
    return con;
    }
    /**
     * Creates new form Asignacion1
     */

    


        
public void llenarCita(){
Connection con=null;
        try {
            con=getConection();
            ps= con.prepareStatement("UPDATE persona SET tipo_cita=7 WHERE telefono="+telefono);
             int res=ps.executeUpdate();
           
            if (res>0){
                JOptionPane.showMessageDialog(null, "Pida una cita por telefono de atencion prioritaria");
            }
            else {
                JOptionPane.showMessageDialog(null,"Error"); 
            }
            
            con.close();
        }
         catch (Exception e){
             System.err.println(e);
         }
    
         } 
        

    public ConsultaExt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirmarMedico = new javax.swing.JButton();
        Continuar = new javax.swing.JButton();

        btnConfirmarMedico.setText("Confirmar");
        btnConfirmarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarMedicoActionPerformed(evt);
            }
        });

        Continuar.setText("Continuar");
        Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Continuar)
                    .addComponent(btnConfirmarMedico))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnConfirmarMedico)
                .addGap(18, 18, 18)
                .addComponent(Continuar)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarMedicoActionPerformed
    llenarCita();
    }//GEN-LAST:event_btnConfirmarMedicoActionPerformed

    private void ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarActionPerformed
      int mensaje=JOptionPane.showConfirmDialog(null,"¿Desea ingresar otro usuario?");
        if  (mensaje==JOptionPane.NO_OPTION) {
       // Final venta=new Final();
       Hospital.Vista.Final venta = new Hospital.Vista.Final();
        HospitalV.Escritorios.add(venta);
        venta.toFront();
        venta.setVisible(true);
        this.dispose(); 
        
    }
         if (mensaje==JOptionPane.YES_OPTION){
        PersonaVista vent=new PersonaVista();
        HospitalV.Escritorios.add(vent);
        vent.toFront();
        vent.setVisible(true);
        this.dispose();
        }
        if (mensaje==JOptionPane.CLOSED_OPTION){
        this.dispose();
        }
                                   
    }//GEN-LAST:event_ContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Continuar;
    public javax.swing.JButton btnConfirmarMedico;
    // End of variables declaration//GEN-END:variables
}
